export const ACCOUNT = {
  PROFILE_MEMBER_ID_TITLE: 'PROFILE_MEMBER_ID_TITLE',
  PROFILE_EMAIL_TITLE: 'PROFILE_EMAIL_TITLE',
  PROFILE_CREATED_AT_TITLE: 'PROFILE_CREATED_AT_TITLE',
  PROFILE_LANGUAGE_TITLE: 'PROFILE_LANGUAGE_TITLE',
  PROFILE_EMAIL_FREQUENCY_TITLE: 'PROFILE_EMAIL_FREQUENCY_TITLE',
  PROFILE_DELETE_ACCOUNT_TITLE: 'PROFILE_DELETE_ACCOUNT_TITLE',
};
