export const ACCOUNT = {
  PROFILE_TITLE: 'PROFILE_TITLE',
  PROFILE_MEMBER_ID_TITLE: 'PROFILE_MEMBER_ID_TITLE',
  PROFILE_EMAIL_TITLE: 'PROFILE_EMAIL_TITLE',
  PROFILE_CREATED_AT_TITLE: 'PROFILE_CREATED_AT_TITLE',
  PROFILE_LANGUAGE_TITLE: 'PROFILE_LANGUAGE_TITLE',
  PROFILE_EMAIL_FREQUENCY_TITLE: 'PROFILE_EMAIL_FREQUENCY_TITLE',
  PROFILE_SAVE_ACTIONS_TITLE: 'PROFILE_SAVE_ACTIONS_TITLE',
  PROFILE_DELETE_ACCOUNT_TITLE: 'PROFILE_DELETE_ACCOUNT_TITLE',

  PROFILE_AVATAR_TITLE: 'PROFILE_AVATAR_TITLE',
  PROFILE_AVATAR_INFORMATION: 'PROFILE_AVATAR_INFORMATION',

  PROFILE_AVATAR_CURRENT_ALT: 'PROFILE_AVATAR_CURRENT_ALT',
  PROFILE_DELETE_ACCOUNT_MODAL_TITLE: 'PROFILE_DELETE_ACCOUNT_MODAL_TITLE',
  PROFILE_DELETE_ACCOUNT_MODAL_INFORMATION:
    'PROFILE_DELETE_ACCOUNT_MODAL_INFORMATION',
  PROFILE_DELETE_ACCOUNT_MODAL_CONFIRM_BUTTON:
    'PROFILE_DELETE_ACCOUNT_MODAL_CONFIRM_BUTTON',
  PROFILE_DELETE_ACCOUNT_BUTTON: 'PROFILE_DELETE_ACCOUNT_BUTTON',
  PROFILE_DELETE_ACCOUNT_INFORMATION: 'PROFILE_DELETE_ACCOUNT_INFORMATION',

  PASSWORD_SETTINGS_TITLE: 'PASSWORD_SETTINGS_TITLE',
  PASSWORD_SETTINGS_CURRENT_LABEL: 'PASSWORD_SETTINGS_CURRENT_LABEL',
  PASSWORD_SETTINGS_NEW_LABEL: 'PASSWORD_SETTINGS_NEW_LABEL',
  PASSWORD_SETTINGS_NEW_CONFIRM_LABEL: 'PASSWORD_SETTINGS_NEW_CONFIRM_LABEL',
  PASSWORD_SETTINGS_CONFIRM_BUTTON: 'PASSWORD_SETTINGS_CONFIRM_BUTTON',
  PASSWORD_SETTINGS_REQUEST_RESET_BUTTON:
    'PASSWORD_SETTINGS_REQUEST_RESET_BUTTON',
  PASSWORD_SETTINGS_CONFIRM_INFORMATION:
    'PASSWORD_SETTINGS_CONFIRM_INFORMATION',
  PASSWORD_SETTINGS_CURRENT_INFORMATION:
    'PASSWORD_SETTINGS_CURRENT_INFORMATION',
};
