export const BUILDER = {
  NEW_ITEM_BUTTON_TOOLTIP: 'NEW_ITEM_BUTTON_TOOLTIP',
  NEW_ITEM_BUTTON: 'NEW_ITEM_BUTTON',
  ITEM_MENU_CREATE_SHORTCUT_MENU_ITEM: 'ITEM_MENU_CREATE_SHORTCUT_MENU_ITEM',
  ITEM_MENU_FLAG_MENU_ITEM: 'ITEM_MENU_FLAG_MENU_ITEM',
  SWITCH_ACCOUNT_BUTTON_SIGNED_IN: 'SWITCH_ACCOUNT_BUTTON_SIGNED_IN',
  SWITCH_ACCOUNT_BUTTON_SIGNED_OUT: 'SWITCH_ACCOUNT_BUTTON_SIGNED_OUT',
  SETTINGS_LINK_SHOW_IFRAME: 'SETTINGS_LINK_SHOW_IFRAME',
  SETTINGS_LINK_SHOW_BUTTON: 'SETTINGS_LINK_SHOW_BUTTON',
  SETTINGS_LINK_SETTINGS_TITLE: 'SETTINGS_LINK_SETTINGS_TITLE',
  SETTINGS_LINK_SETTINGS_INFORMATIONS: 'SETTINGS_LINK_SETTINGS_INFORMATIONS',
  SETTINGS_THUMBNAIL_TITLE: 'SETTINGS_THUMBNAIL_TITLE',
  THUMBNAIL_SETTING_MY_THUMBNAIL_ALT: 'THUMBNAIL_SETTING_MY_THUMBNAIL_ALT',
  SETTINGS_THUMBNAIL_SETTINGS_INFORMATIONS:
    'SETTINGS_THUMBNAIL_SETTINGS_INFORMATIONS',
  EDIT_ITEM_ERROR_MESSAGE: 'EDIT_ITEM_ERROR_MESSAGE',
  EDIT_ITEM_MODAL_TITLE: 'EDIT_ITEM_MODAL_TITLE',
  ITEM_TAGS_TITLE: 'ITEM_TAGS_TITLE',
  ITEM_TAGS_LABEL: 'ITEM_TAGS_LABEL',
  ITEM_TAGS_INFORMATION: 'ITEM_TAGS_INFORMATION',
  ITEM_TAGS_PREVIEW_TITLE: 'ITEM_TAGS_PREVIEW_TITLE',
  HIDE_ITEM_SHOW_TEXT: 'HIDE_ITEM_SHOW_TEXT',
  HIDE_ITEM_HIDE_TEXT: 'HIDE_ITEM_HIDE_TEXT',
  HIDE_ITEM_HIDDEN_PARENT_INFORMATION: 'HIDE_ITEM_HIDDEN_PARENT_INFORMATION',
  FAVORITE_ITEM_REMOVE_TEXT: 'FAVORITE_ITEM_REMOVE_TEXT',
  FAVORITE_ITEM_ADD_TEXT: 'FAVORITE_ITEM_ADD_TEXT',

  EDIT_ITEM_BUTTON: 'EDIT_ITEM_BUTTON',
  ANALYTICS_DASHBOARD_LABEL: 'ANALYTICS_DASHBOARD_LABEL',
  COLLAPSE_ITEM_COLLAPSE_TEXT: 'COLLAPSE_ITEM_COLLAPSE_TEXT',
  COLLAPSE_ITEM_UNCOLLAPSE_TEXT: 'COLLAPSE_ITEM_UNCOLLAPSE_TEXT',
  CROP_IMAGE_MODAL_TITLE: 'CROP_IMAGE_MODAL_TITLE',
  CROP_IMAGE_MODAL_CONTENT_TEXT: 'CROP_IMAGE_MODAL_CONTENT_TEXT',

  CONFIRM_BUTTON: 'CONFIRM_BUTTON',
  AVATAR_DEFAULT_ALT: 'AVATAR_DEFAULT_ALT',

  MOVE_BUTTON: 'MOVE_BUTTON',

  PIN_ITEM_PIN_TEXT: 'PIN_ITEM_PIN_TEXT',
  PIN_ITEM_UNPIN_TEXT: 'PIN_ITEM_UNPIN_TEXT',
  PLAY_BUTTON_TOOLTIP: 'PLAY_BUTTON_TOOLTIP',

  LIBRARY_SETTINGS_BUTTON_TITLE: 'LIBRARY_SETTINGS_BUTTON_TITLE',
  RECYCLE_ITEM_BUTTON: 'RECYCLE_ITEM_BUTTON',
  RESTORE_ITEM_BUTTON: 'RESTORE_ITEM_BUTTON',
  SHARE_ITEM_BUTTON: 'SHARE_ITEM_BUTTON',
  ITEM_METADATA_CREATOR_TITLE: 'ITEM_METADATA_CREATOR_TITLE',
  ITEM_METADATA_TYPE_TITLE: 'ITEM_METADATA_TYPE_TITLE',
  USER_SWITCH_PROFILE_BUTTON: 'USER_SWITCH_PROFILE_BUTTON',
  USER_SWITCH_SIGNED_OUT_TOOLTIP: 'USER_SWITCH_SIGNED_OUT_TOOLTIP',
  USER_SWITCH_SWITCH_USER_TEXT: 'USER_SWITCH_SWITCH_USER_TEXT',

  ACCESS_ITEM_LOGIN_TAG: 'ACCESS_ITEM_LOGIN_TAG',
  ACCESS_PUBLIC_TAG: 'ACCESS_PUBLIC_TAG',
  ACCESS_PUBLIC_TAG_TOOLTIP: 'ACCESS_PUBLIC_TAG_TOOLTIP',
  ACCESS_ITEM_LOGIN_TAG_TOOLTIP: 'ACCESS_ITEM_LOGIN_TAG_TOOLTIP',
  ACCESS_TITLE: 'ACCESS_TITLE',
  RECYCLE_BIN_TITLE: 'RECYCLE_BIN_TITLE',

  SETTINGS_COLLAPSE_LABEL: 'SETTINGS_COLLAPSE_LABEL',
  SETTINGS_PIN_ITEM_LABEL: 'SETTINGS_PIN_ITEM_LABEL',
  SETTINGS_SHOW_CHAT_LABEL: 'SETTINGS_SHOW_CHAT_LABEL',
  SETTINGS_RESIZE_LABEL: 'SETTINGS_RESIZE_LABEL',
  SETTINGS_TITLE: 'SETTINGS_TITLE',
  SETTINGS_COLLAPSE_FOLDER_INFORMATION: 'SETTINGS_COLLAPSE_FOLDER_INFORMATION',

  LIBRARY_SETTINGS_INFORMATION: 'LIBRARY_SETTINGS_INFORMATION',
  LIBRARY_SETTINGS_TITLE: 'LIBRARY_SETTINGS_TITLE',
  LIBRARY_SETTINGS_VALIDATION_TITLE: 'LIBRARY_SETTINGS_VALIDATION_TITLE',

  LIBRARY_SETTINGS_VISIBILITY_INFORMATIONS: 'LIBRARY_SETTINGS_VISIBILITY_INFORMATIONS',

  SHARE_ITEM_CSV_IMPORT_MODAL_TITLE: 'SHARE_ITEM_CSV_IMPORT_MODAL_TITLE',
  SHARE_ITEM_CSV_IMPORT_SUCCESS_MESSAGE:
    'SHARE_ITEM_CSV_IMPORT_SUCCESS_MESSAGE',
  SHARE_ITEM_CSV_IMPORT_MODAL_CONTENT: 'SHARE_ITEM_CSV_IMPORT_MODAL_CONTENT',
  SHARE_ITEM_CSV_IMPORT_INPUT_BUTTON: 'SHARE_ITEM_CSV_IMPORT_INPUT_BUTTON',
  SHARE_ITEM_CSV_IMPORT_ERROR_MESSAGE: 'SHARE_ITEM_CSV_IMPORT_ERROR_MESSAGE',
  SHARE_ITEM_FORM_EMAIL_LABEL: 'SHARE_ITEM_FORM_EMAIL_LABEL',
  SHARE_ITEM_FORM_CONFIRM_BUTTON: 'SHARE_ITEM_FORM_CONFIRM_BUTTON',
  SHARE_ITEM_FORM_INVITATION_TOOLTIP: 'SHARE_ITEM_FORM_INVITATION_TOOLTIP',

  SHARE_ITEM_FORM_INVITATION_EMAIL_EXISTS_MESSAGE:
    'SHARE_ITEM_FORM_INVITATION_EMAIL_EXISTS_MESSAGE',
  SHARE_ITEM_FORM_INVITATION_INVALID_EMAIL_MESSAGE:
    'SHARE_ITEM_FORM_INVITATION_INVALID_EMAIL_MESSAGE',
  SHARE_ITEM_FORM_INVITATION_EMPTY_EMAIL_MESSAGE:
    'SHARE_ITEM_FORM_INVITATION_EMPTY_EMAIL_MESSAGE',
  INVITATIONS_TABLE_CANNOT_DELETE_PARENT_TOOLTIP:
    'INVITATIONS_TABLE_CANNOT_DELETE_PARENT_TOOLTIP',
  INVITATIONS_TABLE_EMAIL_HEADER: 'INVITATIONS_TABLE_EMAIL_HEADER',
  INVITATIONS_TABLE_INVITATION_HEADER: 'INVITATIONS_TABLE_INVITATION_HEADER',
  INVITATIONS_TABLE_PERMISSION_HEADER: 'INVITATIONS_TABLE_PERMISSION_HEADER',
  INVITATIONS_TABLE_ACTIONS_HEADER: 'INVITATIONS_TABLE_ACTIONS_HEADER',
  CREATE_NEW_ITEM_DOCUMENT_TITLE: 'CREATE_NEW_ITEM_DOCUMENT_TITLE',
  TEXT_EDITOR_PLACEHOLDER: 'TEXT_EDITOR_PLACEHOLDER',
  CREATE_NEW_ITEM_NAME_LABEL: 'CREATE_NEW_ITEM_NAME_LABEL',
  CREATE_NEW_ITEM_APP_TITLE: 'CREATE_NEW_ITEM_APP_TITLE',
  CREATE_ITEM_NEW_FOLDER_TITLE: 'CREATE_ITEM_NEW_FOLDER_TITLE',
  CREATE_NEW_ITEM_APP_URL_LABEL: 'CREATE_NEW_ITEM_APP_URL_LABEL',
  ITEM_MEMBERSHIP_PERMISSION_LABEL: 'ITEM_MEMBERSHIP_PERMISSION_LABEL',
  ITEM_MEMBERSHIPS_TABLE_CANNOT_DELETE_PARENT_TOOLTIP:
    'ITEM_MEMBERSHIPS_TABLE_CANNOT_DELETE_PARENT_TOOLTIP',
  ITEM_MEMBERSHIPS_TABLE_EMAIL_HEADER: 'ITEM_MEMBERSHIPS_TABLE_EMAIL_HEADER',
  ITEM_MEMBERSHIPS_TABLE_NAME_HEADER: 'ITEM_MEMBERSHIPS_TABLE_NAME_HEADER',
  ITEM_MEMBERSHIPS_TABLE_PERMISSION_HEADER:
    'ITEM_MEMBERSHIPS_TABLE_PERMISSION_HEADER',
  ITEM_MEMBERSHIPS_TABLE_ACTIONS_HEADER:
    'ITEM_MEMBERSHIPS_TABLE_ACTIONS_HEADER',
  EDIT_FOLDER_DESCRIPTION_PLACEHOLDER: 'EDIT_FOLDER_DESCRIPTION_PLACEHOLDER',
  SHARING_AUTHORIZED_MEMBERS_TITLE: 'SHARING_AUTHORIZED_MEMBERS_TITLE',
  SHARING_AUTHENTICATED_MEMBERS_TITLE: 'SHARING_AUTHENTICATED_MEMBERS_TITLE',
  SHARING_AUTHORIZED_MEMBERS_EMPTY_MESSAGE:
    'SHARING_AUTHORIZED_MEMBERS_EMPTY_MESSAGE',
  SHARING_AUTHENTICATED_MEMBERS_EMPTY_MESSAGE:
    'SHARING_AUTHENTICATED_MEMBERS_EMPTY_MESSAGE',
  SHARING_INVITATIONS_TITLE: 'SHARING_INVITATIONS_TITLE',
  SHARING_INVITATIONS_EMPTY_MESSAGE: 'SHARING_INVITATIONS_EMPTY_MESSAGE',
  SHARING_TITLE: 'SHARING_TITLE',
  SHARING_INVITATIONS_RESEND_BUTTON: 'SHARING_INVITATIONS_RESEND_BUTTON',
  NEW_ITEM_FOLDER_TAB_TEXT: 'NEW_ITEM_FOLDER_TAB_TEXT',
  NEW_ITEM_H5P_TAB_TEXT: 'NEW_ITEM_H5P_TAB_TEXT',
  NEW_ITEM_APP_TAB_TEXT: 'NEW_ITEM_APP_TAB_TEXT',
  NEW_ITEM_LINK_TAB_TEXT: 'NEW_ITEM_LINK_TAB_TEXT',
  NEW_ITEM_DOCUMENT_TAB_TEXT: 'NEW_ITEM_DOCUMENT_TAB_TEXT',
  NEW_ITEM_FILE_TAB_TEXT: 'NEW_ITEM_FILE_TAB_TEXT',
  NEW_ITEM_ZIP_TAB_TEXT: 'NEW_ITEM_ZIP_TAB_TEXT',

  ITEMS_TABLE_UPDATED_AT_HEADER: 'ITEMS_TABLE_UPDATED_AT_HEADER',
  ITEMS_TABLE_ACTIONS_HEADER: 'ITEMS_TABLE_ACTIONS_HEADER',
  ITEMS_TABLE_CREATOR_HEADER: 'ITEMS_TABLE_CREATOR_HEADER',
  ITEMS_TABLE_TYPE_HEADER: 'ITEMS_TABLE_TYPE_HEADER',
  ITEMS_TABLE_NAME_HEADER: 'ITEMS_TABLE_NAME_HEADER',
  ITEMS_TABLE_EMPTY_MESSAGE: 'ITEMS_TABLE_EMPTY_MESSAGE',
  ITEMS_TABLE_DRAG_DEFAULT_MESSAGE: 'ITEMS_TABLE_DRAG_DEFAULT_MESSAGE',

  ITEMS_GRID_ITEMS_PER_PAGE_TITLE: 'ITEMS_GRID_ITEMS_PER_PAGE_TITLE',
  USER_SWITCH_SIGN_OUT_BUTTON: 'USER_SWITCH_SIGN_OUT_BUTTON',
  ERROR_MESSAGE: 'ERROR_MESSAGE',
  DELETE_BUTTON: 'DELETE_BUTTON',

  EDIT_BUTTON_TOOLTIP: 'EDIT_BUTTON_TOOLTIP',
  IMPORT_ZIP_INFORMATION: 'IMPORT_ZIP_INFORMATION',
  IMPORT_ZIP_WARNING: 'IMPORT_ZIP_WARNING',
  IMPORT_ZIP_TITLE: 'IMPORT_ZIP_TITLE',
  IMPORT_ZIP_LIMITATIONS_TEXT: 'IMPORT_ZIP_LIMITATIONS_TEXT',
  IMPORT_H5P_TITLE: 'IMPORT_H5P_TITLE',

  IMPORT_H5P_INFORMATIONS: 'IMPORT_H5P_INFORMATIONS',
  IMPORT_H5P_WARNING: 'IMPORT_H5P_WARNING',
  IMPORT_H5P_LIMITATIONS_TEXT: 'IMPORT_H5P_LIMITATIONS_TEXT',
  COPY_ITEM_MODAL_TITLE: 'COPY_ITEM_MODAL_TITLE',
  CREATE_SHORTCUT_MODAL_TITLE: 'CREATE_SHORTCUT_MODAL_TITLE',
  FLAG_ITEM_MODAL_TITLE: 'FLAG_ITEM_MODAL_TITLE',
  FLAG_ITEM_REASON_TITLE: 'FLAG_ITEM_REASON_TITLE',
  FLAG_ITEM_BUTTON: 'FLAG_ITEM_BUTTON',

  MOVE_ITEM_MODAL_TITLE: 'MOVE_ITEM_MODAL_TITLE',
  UPLOAD_FILE_INFORMATIONS: 'UPLOAD_FILE_INFORMATIONS',
  UPLOAD_FILE_LIMITATIONS_TEXT: 'UPLOAD_FILE_LIMITATIONS_TEXT',
  UPLOAD_FILE_TITLE: 'UPLOAD_FILE_TITLE',
  UPLOAD_FILE_BROWSE: 'UPLOAD_FILE_BROWSE',
  UPLOAD_FILE_DROP_TEXT: 'UPLOAD_FILE_DROP_TEXT',
  LINK_DEFAULT_NAME: 'LINK_DEFAULT_NAME',
  CREATE_ITEM_FOLDER_TITLE: 'CREATE_ITEM_FOLDER_TITLE',

  CREATE_ITEM_LINK_TITLE: 'CREATE_ITEM_LINK_TITLE',
  CREATE_ITEM_DOCUMENT_TITLE: 'CREATE_ITEM_DOCUMENT_TITLE',
  CREATE_ITEM_APP_TITLE: 'CREATE_ITEM_APP_TITLE',
  CREATE_ITEM_LINK_INVALID_LINK_ERROR: 'CREATE_ITEM_LINK_INVALID_LINK_ERROR',
  CREATE_ITEM_LINK_LABEL: 'CREATE_ITEM_LINK_LABEL',
  LAYOUT_MODE_LIST_LABEL: 'LAYOUT_MODE_LIST_LABEL',
  LAYOUT_MODE_GRID_LABEL: 'LAYOUT_MODE_GRID_LABEL',
  ITEM_CATEGORIES_SELECTION_TITLE: 'ITEM_CATEGORIES_SELECTION_TITLE',
  ITEM_SETTINGS_CC_LICENSE_MODAL_TITLE: 'ITEM_SETTINGS_CC_LICENSE_MODAL_TITLE',
  ITEM_SETTINGS_CC_LICENSE_MODAL_CONTENT:
    'ITEM_SETTINGS_CC_LICENSE_MODAL_CONTENT',
  ITEM_SETTINGS_CC_LICENSE_TITLE: 'ITEM_SETTINGS_CC_LICENSE_TITLE',
  ITEM_SETTINGS_CC_LICENSE_MORE_INFORMATIONS:
    'ITEM_SETTINGS_CC_LICENSE_MORE_INFORMATIONS',
  ITEM_SETTINGS_CC_LICENSE_INFORMATIONS:
    'ITEM_SETTINGS_CC_LICENSE_INFORMATIONS',
  ITEM_SETTINGS_CC_LICENSE_LABEL: 'ITEM_SETTINGS_CC_LICENSE_LABEL',
  ITEM_SETTINGS_CC_LICENSE_ALIKE_LABEL: 'ITEM_SETTINGS_CC_LICENSE_ALIKE_LABEL',
  ITEM_SETTINGS_CC_LICENSE_NONE_LABEL: 'ITEM_SETTINGS_CC_LICENSE_NONE_LABEL',
  ITEM_SETTINGS_CC_LICENSE_ALLOW_LABEL: 'ITEM_SETTINGS_CC_LICENSE_ALLOW_LABEL',
  ITEM_SETTINGS_CC_LICENSE_SUBMIT_BUTTON:
    'ITEM_SETTINGS_CC_LICENSE_SUBMIT_BUTTON',
  ITEM_SETTINGS_CO_EDITORS_TITLE: 'ITEM_SETTINGS_CO_EDITORS_TITLE',
  ITEM_SETTINGS_CO_EDITORS_INFORMATIONS:
    'ITEM_SETTINGS_CO_EDITORS_INFORMATIONS',
  ITEM_SETTINGS_CO_EDITORS_LABEL: 'ITEM_SETTINGS_CO_EDITORS_LABEL',
  DROP_DOWN_PLACEHOLDER: 'DROP_DOWN_PLACEHOLDER',
  LIBRARY_SETTINGS_UNPUBLISH_BUTTON: 'LIBRARY_SETTINGS_UNPUBLISH_BUTTON',
  LIBRARY_SETTINGS_PUBLISH_BUTTON: 'LIBRARY_SETTINGS_PUBLISH_BUTTON',
  LIBRARY_SETTINGS_PUBLISH_NOTIFICATIONS_LABEL:
    'LIBRARY_SETTINGS_PUBLISH_NOTIFICATIONS_LABEL',
  LIBRARY_SETTINGS_PUBLISHED_STATUS: 'LIBRARY_SETTINGS_PUBLISHED_STATUS',
  LIBRARY_SETTINGS_VALIDATION_STATUS_PENDING_MANUAL:
    'LIBRARY_SETTINGS_VALIDATION_STATUS_PENDING_MANUAL',
  LIBRARY_SETTINGS_VALIDATION_STATUS_PENDING_AUTOMATIC:
    'LIBRARY_SETTINGS_VALIDATION_STATUS_PENDING_AUTOMATIC',
  LIBRARY_SETTINGS_VALIDATION_STATUS_FAILURE:
    'LIBRARY_SETTINGS_VALIDATION_STATUS_FAILURE',
  LIBRARY_SETTINGS_VALIDATION_INFORMATIONS:
    'LIBRARY_SETTINGS_VALIDATION_INFORMATIONS',
  LIBRARY_SETTINGS_VALIDATION_VALIDATE_BUTTON:
    'LIBRARY_SETTINGS_VALIDATION_VALIDATE_BUTTON',
  LIBRARY_SETTINGS_VALIDATION_REFRESH_BUTTON:
    'LIBRARY_SETTINGS_VALIDATION_REFRESH_BUTTON',
  LIBRARY_SETTINGS_VALIDATION_PUBLICATION_TITLE:
    'LIBRARY_SETTINGS_VALIDATION_PUBLICATION_TITLE',
  LIBRARY_SETTINGS_VALIDATION_PUBLICATION_INFORMATIONS:
    'LIBRARY_SETTINGS_VALIDATION_PUBLICATION_INFORMATIONS',
  LIBRARY_SETTINGS_VALIDATION_CONFIGURATION_TITLE:
    'LIBRARY_SETTINGS_VALIDATION_CONFIGURATION_TITLE',
  LIBRARY_SETTINGS_VALIDATION_CONFIGURATION_INFORMATIONS:
    'LIBRARY_SETTINGS_VALIDATION_CONFIGURATION_INFORMATIONS',
  LIBRARY_SETTINGS_NOT_PUBLISHED_ITEM_MESSAGE:
    'LIBRARY_SETTINGS_NOT_PUBLISHED_ITEM_MESSAGE',
  SHARE_ITEM_CSV_IMPORT_BUTTON: 'SHARE_ITEM_CSV_IMPORT_BUTTON',
  SHARE_ITEM_LINK_COPY_TOOLTIP: 'SHARE_ITEM_LINK_COPY_TOOLTIP',
  ITEM_SETTINGS_VISIBILITY_PRIVATE_LABEL:
    'ITEM_SETTINGS_VISIBILITY_PRIVATE_LABEL',
  ITEM_SETTINGS_VISIBILITY_TITLE: 'ITEM_SETTINGS_VISIBILITY_TITLE',
  ITEM_SETTINGS_VISIBILITY_PUBLIC_LABEL:
    'ITEM_SETTINGS_VISIBILITY_PUBLIC_LABEL',
  ITEM_SETTINGS_VISIBILITY_PSEUDONYMIZED_LABEL:
    'ITEM_SETTINGS_VISIBILITY_PSEUDONYMIZED_LABEL',
  ITEM_SETTINGS_VISIBILITY_CANNOT_EDIT_PARENT_MESSAGE:
    'ITEM_SETTINGS_VISIBILITY_CANNOT_EDIT_PARENT_MESSAGE',
  ITEM_SETTINGS_VISIBILITY_PRIVATE_INFORMATION:
    'ITEM_SETTINGS_VISIBILITY_PRIVATE_INFORMATION',
  ITEM_SETTINGS_VISIBILITY_PSEUDONYMIZED_SCHEMA_SELECT_MESSSAGE:
    'ITEM_SETTINGS_VISIBILITY_PSEUDONYMIZED_SCHEMA_SELECT_MESSSAGE',

  ITEM_SETTINGS_VISIBILITY_PSEUDONYMIZED_SCHEMA_PSEUDONYM_AND_PASSWORD_LABEL:
    'ITEM_SETTINGS_VISIBILITY_PSEUDONYMIZED_SCHEMA_PSEUDONYM_AND_PASSWORD_LABEL',

  ITEM_SETTINGS_VISIBILITY_PSEUDONYMIZED_SCHEMA_PSEUDONYM_LABEL:
    'ITEM_SETTINGS_VISIBILITY_PSEUDONYMIZED_SCHEMA_PSEUDONYM_LABEL',
  ITEM_CHATBOX_TITLE: 'ITEM_CHATBOX_TITLE',
  ITEM_METADATA_TITLE: 'ITEM_METADATA_TITLE',
  SHARED_MEMBERS_TOOLTIP: 'SHARED_MEMBERS_TOOLTIP',
  SHARED_MEMBERS_LABEL: 'SHARED_MEMBERS_LABEL',
  ITEM_METADATA_SIZE_TITLE: 'ITEM_METADATA_SIZE_TITLE',
  ITEM_METADATA_LINK_TITLE: 'ITEM_METADATA_LINK_TITLE',
  ITEM_METADATA_CREATED_AT_TITLE: 'ITEM_METADATA_CREATED_AT_TITLE',
  ITEM_METADATA_UPDATED_AT_TITLE: 'ITEM_METADATA_UPDATED_AT_TITLE',
  ITEM_SEARCH_NO_RESULTS_MESSAGE: 'ITEM_SEARCH_NO_RESULTS_MESSAGE',
  NAVIGATION_MY_ITEMS_TITLE: 'NAVIGATION_MY_ITEMS_TITLE',
  NAVIGATION_FAVORITE_ITEMS_TITLE: 'NAVIGATION_FAVORITE_ITEMS_TITLE',
  NAVIGATION_SHARED_ITEMS_TITLE: 'NAVIGATION_SHARED_ITEMS_TITLE',
  SHARED_ITEMS_TITLE: 'SHARED_ITEMS_TITLE',
  FAVORITE_ITEMS_TITLE: 'FAVORITE_ITEMS_TITLE',
  ITEM_COPY_BUTTON: 'ITEM_COPY_BUTTON',
  DELETE_ITEM_MODAL_TITLE: 'DELETE_ITEM_MODAL_TITLE',
  DELETE_ITEM_MODAL_CONFIRM_BUTTON: 'DELETE_ITEM_MODAL_CONFIRM_BUTTON',
  DELETE_ITEM_MODAL_CONTENT: 'DELETE_ITEM_MODAL_CONTENT',
  DOWNLOAD_ITEM_BUTTON: 'DOWNLOAD_ITEM_BUTTON',
  EMPTY_ITEM_MESSAGE: 'EMPTY_ITEM_MESSAGE',
  MY_ITEMS_TITLE: 'MY_ITEMS_TITLE',
  ITEMS_TABLE_SELECTION_TEXT: 'ITEMS_TABLE_SELECTION_TEXT',
  CREATE_ITEM_ADD_BUTTON: 'CREATE_ITEM_ADD_BUTTON',
  TABLE_SELECT_ALL_LABEL: 'TABLE_SELECT_ALL_LABEL',
  TABLE_DESC_SORT_LABEL: 'TABLE_DESC_SORT_LABEL',
  TABLE_ASC_SORT_LABEL: 'TABLE_ASC_SORT_LABEL',
  ITEMS_TREE_OWN_ITEMS_LABEL: 'ITEMS_TREE_OWN_ITEMS_LABEL',
  TREE_MODAL_CONFIRM_BUTTON: 'TREE_MODAL_CONFIRM_BUTTON',
  ITEM_SEARCH_PLACEHOLDER: 'ITEM_SEARCH_PLACEHOLDER',
  HOME_TITLE: 'HOME_TITLE',
  ITEM_SETTINGS_CC_LICENSE_PREVIEW_TITLE:
    'ITEM_SETTINGS_CC_LICENSE_PREVIEW_TITLE',
  ITEM_SETTINGS_VISIBILITY_PUBLIC_INFORMATIONS:
    'ITEM_SETTINGS_VISIBILITY_PUBLIC_INFORMATIONS',

  CREATE_SHORTCUT_DEFAULT_NAME: 'CREATE_SHORTCUT_DEFAULT_NAME',
};
