export const BUILDER = {
  NEW_ITEM_BUTTON_TOOLTIP: 'NEW_ITEM_BUTTON_TOOLTIP',
  NEW_ITEM_BUTTON: 'NEW_ITEM_BUTTON',
  ITEM_MENU_CREATE_SHORTCUT_MENU_ITEM: 'ITEM_MENU_CREATE_SHORTCUT_MENU_ITEM',
  ITEM_MENU_FLAG_MENU_ITEM: 'ITEM_MENU_FLAG_MENU_ITEM',
  SWITCH_ACCOUNT_BUTTON_SIGNED_IN: 'SWITCH_ACCOUNT_BUTTON_SIGNED_IN',
  SWITCH_ACCOUNT_BUTTON_SIGNED_OUT: 'SWITCH_ACCOUNT_BUTTON_SIGNED_OUT',
  SETTINGS_LINK_SHOW_IFRAME: 'SETTINGS_LINK_SHOW_IFRAME',
  SETTINGS_LINK_SHOW_BUTTON: 'SETTINGS_LINK_SHOW_BUTTON',
  SETTINGS_LINK_SETTINGS_TITLE: 'SETTINGS_LINK_SETTINGS_TITLE',
  SETTINGS_LINK_SETTINGS_INFORMATIONS: 'SETTINGS_LINK_SETTINGS_INFORMATIONS',
  SETTINGS_THUMBNAIL_TITLE: 'SETTINGS_THUMBNAIL_TITLE',
  THUMBNAIL_SETTING_MY_THUMBNAIL_ALT: 'THUMBNAIL_SETTING_MY_THUMBNAIL_ALT',
  SETTINGS_THUMBNAIL_SETTINGS_INFORMATIONS:
    'SETTINGS_THUMBNAIL_SETTINGS_INFORMATIONS',
  EDIT_ITEM_ERROR_MESSAGE: 'EDIT_ITEM_ERROR_MESSAGE',
  EDIT_ITEM_MODAL_TITLE: 'EDIT_ITEM_MODAL_TITLE',
  ITEM_TAGS_TITLE: 'ITEM_TAGS_TITLE',
  ITEM_TAGS_LABEL: 'ITEM_TAGS_LABEL',
  ITEM_TAGS_INFORMATION: 'ITEM_TAGS_INFORMATION',
  ITEM_TAGS_PREVIEW_TITLE: 'ITEM_TAGS_PREVIEW_TITLE',
  HIDE_ITEM_SHOW_TEXT: 'HIDE_ITEM_SHOW_TEXT',
  HIDE_ITEM_HIDE_TEXT: 'HIDE_ITEM_HIDE_TEXT',
  HIDE_ITEM_HIDDEN_PARENT_INFORMATION: 'HIDE_ITEM_HIDDEN_PARENT_INFORMATION',
  FAVORITE_ITEM_REMOVE_TEXT: 'FAVORITE_ITEM_REMOVE_TEXT',
  FAVORITE_ITEM_ADD_TEXT: 'FAVORITE_ITEM_ADD_TEXT',

  EDIT_ITEM_BUTTON: 'EDIT_ITEM_BUTTON',
  ANALYTICS_DASHBOARD_LABEL: 'ANALYTICS_DASHBOARD_LABEL',
  COLLAPSE_ITEM_COLLAPSE_TEXT: 'COLLAPSE_ITEM_COLLAPSE_TEXT',
  COLLAPSE_ITEM_UNCOLLAPSE_TEXT: 'COLLAPSE_ITEM_UNCOLLAPSE_TEXT',
  CROP_IMAGE_MODAL_TITLE: 'CROP_IMAGE_MODAL_TITLE',
  CROP_IMAGE_MODAL_CONTENT_TEXT: 'CROP_IMAGE_MODAL_CONTENT_TEXT',

  CONFIRM_BUTTON: 'CONFIRM_BUTTON',
  AVATAR_DEFAULT_ALT: 'AVATAR_DEFAULT_ALT',

  MOVE_BUTTON: 'MOVE_BUTTON',

  PIN_ITEM_PIN_TEXT: 'PIN_ITEM_PIN_TEXT',
  PIN_ITEM_UNPIN_TEXT: 'PIN_ITEM_UNPIN_TEXT',
  PLAY_BUTTON_TOOLTIP: 'PLAY_BUTTON_TOOLTIP',

  LIBRARY_SETTINGS_BUTTON_TITLE: 'LIBRARY_SETTINGS_BUTTON_TITLE',
  RECYCLE_ITEM_BUTTON: 'RECYCLE_ITEM_BUTTON',
  RESTORE_ITEM_BUTTON: 'RESTORE_ITEM_BUTTON',
  SHARE_ITEM_BUTTON: 'SHARE_ITEM_BUTTON',

  USER_SWITCH_PROFILE_BUTTON: 'USER_SWITCH_PROFILE_BUTTON',
  USER_SWITCH_SIGNED_OUT_TOOLTIP: 'USER_SWITCH_SIGNED_OUT_TOOLTIP',
  USER_SWITCH_SWITCH_USER_TEXT: 'USER_SWITCH_SWITCH_USER_TEXT',

  ACCESS_ITEM_LOGIN_TAG: 'ACCESS_ITEM_LOGIN_TAG',
  ACCESS_PUBLIC_TAG: 'ACCESS_PUBLIC_TAG',
  ACCESS_PUBLIC_TAG_TOOLTIP: 'ACCESS_PUBLIC_TAG_TOOLTIP',
  ACCESS_ITEM_LOGIN_TAG_TOOLTIP: 'ACCESS_ITEM_LOGIN_TAG_TOOLTIP',
  ACCESS_TITLE: 'ACCESS_TITLE',

  RECYCLE_BIN_TITLE: 'RECYCLE_BIN_TITLE',

  PASSWORD_SETTINGS_TITLE: 'PASSWORD_SETTINGS_TITLE',
  PASSWORD_SETTINGS_CURRENT_LABEL: 'PASSWORD_SETTINGS_CURRENT_LABEL',
  PASSWORD_SETTINGS_NEW_LABEL: 'PASSWORD_SETTINGS_NEW_LABEL',
  PASSWORD_SETTINGS_NEW_CONFIRM_LABEL: 'PASSWORD_SETTINGS_NEW_CONFIRM_LABEL',
  PASSWORD_SETTINGS_CONFIRM_BUTTON: 'PASSWORD_SETTINGS_CONFIRM_BUTTON',
  PASSWORD_SETTINGS_REQUEST_RESET_BUTTON:
    'PASSWORD_SETTINGS_REQUEST_RESET_BUTTON',
  PASSWORD_SETTINGS_CONFIRM_INFORMATION:
    'PASSWORD_SETTINGS_CONFIRM_INFORMATION',

  SETTINGS_COLLAPSE_LABEL: 'SETTINGS_COLLAPSE_LABEL',
  SETTINGS_PIN_ITEM_LABEL: 'SETTINGS_PIN_ITEM_LABEL',
  SETTINGS_SHOW_CHAT_LABEL: 'SETTINGS_SHOW_CHAT_LABEL',
  SETTINGS_TITLE: 'SETTINGS_TITLE',
  SETTINGS_COLLAPSE_FOLDER_INFORMATION: 'SETTINGS_COLLAPSE_FOLDER_INFORMATION',

  LIBRARY_SETTINGS_INFORMATION: 'LIBRARY_SETTINGS_INFORMATION',
  LIBRARY_SETTINGS_TITLE: 'LIBRARY_SETTINGS_TITLE',
  LIBRARY_SETTINGS_VALIDATION_TITLE: 'LIBRARY_SETTINGS_VALIDATION_TITLE',

  SHARE_ITEM_CSV_IMPORT_MODAL_TITLE: 'SHARE_ITEM_CSV_IMPORT_TITLE',
  SHARE_ITEM_CSV_IMPORT_SUCCESS_MESSAGE:
    'SHARE_ITEM_CSV_IMPORT_SUCCESS_MESSAGE',
  SHARE_ITEM_CSV_IMPORT_MODAL_CONTENT: 'SHARE_ITEM_CSV_IMPORT_MODAL_CONTENT',
  SHARE_ITEM_CSV_IMPORT_INPUT_BUTTON: 'SHARE_ITEM_CSV_IMPORT_INPUT_BUTTON',
  SHARE_ITEM_CSV_IMPORT_ERROR_MESSAGE: 'SHARE_ITEM_CSV_IMPORT_ERROR_MESSAGE',
  SHARE_ITEM_FORM_EMAIL_LABEL: 'SHARE_ITEM_FORM_EMAIL_LABEL',
  SHARE_ITEM_FORM_CONFIRM_BUTTON: 'SHARE_ITEM_FORM_CONFIRM_BUTTON',
  SHARE_ITEM_FORM_INVITATION_TOOLTIP: 'SHARE_ITEM_FORM_INVITATION_TOOLTIP',

  SHARE_ITEM_FORM_INVITATION_EMAIL_EXISTS_MESSAGE:
    'SHARE_ITEM_FORM_INVITATION_EMAIL_EXISTS_MESSAGE',
  SHARE_ITEM_FORM_INVITATION_INVALID_EMAIL_MESSAGE:
    'SHARE_ITEM_FORM_INVITATION_INVALID_EMAIL_MESSAGE',
  SHARE_ITEM_FORM_INVITATION_EMPTY_EMAIL_MESSAGE:
    'SHARE_ITEM_FORM_INVITATION_EMPTY_EMAIL_MESSAGE',
  INVITATIONS_TABLE_CANNOT_DELETE_PARENT_TOOLTIP:
    'INVITATIONS_TABLE_CANNOT_DELETE_PARENT_TOOLTIP',
  INVITATIONS_TABLE_EMAIL_HEADER: 'INVITATIONS_TABLE_EMAIL_HEADER',
  INVITATIONS_TABLE_INVITATION_HEADER: 'INVITATIONS_TABLE_INVITATION_HEADER',
  INVITATIONS_TABLE_PERMISSION_HEADER: 'INVITATIONS_TABLE_PERMISSION_HEADER',
  INVITATIONS_TABLE_ACTIONS_HEADER: 'INVITATIONS_TABLE_ACTIONS_HEADER',
};
