export const CATEGORIES = {
  // category types
  LANGUAGE: 'LANGUAGE',
  DISCIPLINE: 'DISCIPLINE',
  EDUCATION_LEVEL: 'EDUCATION_LEVEL',

  // disciplines
  MATH: 'MATH',
  LITERATURE: 'LITERATURE',
  // LANGUAGE: "LANGUAGE",
  SOCIAL_SCIENCE: 'SOCIAL_SCIENCE',
  NATURAL_SCIENCE: 'NATURAL_SCIENCE',
  ARTS: 'ARTS',

  // education levels
  KINDERGARTEN: 'KINDERGARTEN',
  PRIMARY_SCHOOL: 'PRIMARY_SCHOOL',
  LOWER_SECONDARY_SCHOOL: 'LOWER_SECONDARY_SCHOOL',
  UPPER_SECONDARY_SCHOOL: 'UPPER_SECONDARY_SCHOOL',
  VOCATIONAL_TRAINING: 'VOCATIONAL_TRAINING',
  HIGHER_EDUCATION: 'HIGHER_EDUCATION',
};
