export const CHATBOX = {
  EDITING_MESSAGE_LABEL: 'EDITING_MESSAGE_LABEL',
  MESSAGE_MODIFIED_INDICATOR: 'MESSAGE_MODIFIED_INDICATOR',
  EDIT_BUTTON: 'EDIT_BUTTON',
  DELETE_BUTTON: 'DELETE_BUTTON',
  INPUT_FIELD_PLACEHOLDER: 'INPUT_FIELD_PLACEHOLDER',
  CHATBOX_HEADER: 'CHATBOX_HEADER',
};
