export const COMMON = {
  COOKIE_BANNER_TEXT: 'COOKIE_BANNER_TEXT',
  COOKIE_BANNER_ACCEPT_BUTTON: 'COOKIE_BANNER_ACCEPT_BUTTON',
  COOKIE_BANNER_DECLINE_BUTTON: 'COOKIE_BANNER_DECLINE_BUTTON',
  AVATAR_DEFAULT_ALT: 'AVATAR_DEFAULT_ALT',
  MEMBER_DEFAULT_NAME: 'MEMBER_DEFAULT_NAME',

  CANCEL_BUTTON: 'CANCEL_BUTTON',
  SAVE_BUTTON: 'SAVE_BUTTON',
  CLOSE_BUTTON: 'CLOSE_BUTTON',
};
