export const COMMON = {
  COOKIE_BANNER_TEXT: 'COOKIE_BANNER_TEXT',
  COOKIE_BANNER_ACCEPT_BUTTON: 'COOKIE_BANNER_ACCEPT_BUTTON',
  COOKIE_BANNER_DECLINE_BUTTON: 'COOKIE_BANNER_DECLINE_BUTTON',
  AVATAR_DEFAULT_ALT: 'AVATAR_DEFAULT_ALT',
  MEMBER_DEFAULT_NAME: 'MEMBER_DEFAULT_NAME',
  UNKNOWN_DATE: 'UNKNOWN_DATE',

  USER_OWN_ITEMS: 'USER_OWN_ITEMS',
  USER_SHARED_WITH_ITEMS: 'USER_SHARED_WITH_ITEMS',
  USER_NOT_SIGNED_IN: 'USER_NOT_SIGNED_IN',
  USER_CAN_NOT_ACCESS_ITEM: 'USER_CAN_NOT_ACCESS_ITEM',

  CHAT_TOOLTIP: 'CHAT_TOOLTIP',

  CANCEL_BUTTON: 'CANCEL_BUTTON',
  SAVE_BUTTON: 'SAVE_BUTTON',
  CLOSE_BUTTON: 'CLOSE_BUTTON',

  LANGUAGE: 'LANGUAGE',
};
