name: Build

on:
  push:
    branches:
      - main
  pull_request:
  merge_group:

jobs:
  build:
    name: Build
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Yarn install and cache dependencies
      uses: graasp/graasp-deploy/.github/actions/yarn-install-and-cache@v1

    - name: Check code styling and linting
      run: yarn check

    - name: Yarn build
      run: yarn build
